name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        uv venv/bin/activate
        uv pip install -r requirements.txt
        uv pip install black isort flake8 mypy
    
    - name: Check formatting with black
      run: |
        uv run -m black --check src/
    
    - name: Check imports with isort
      run: |
        uv run -m isort --check-only --profile black src/
    
    - name: Lint with flake8
      run: |
        uv run -m flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        uv run -m flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Type check with mypy
      run: |
        uv run -m mypy src/
