name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        uv .venv/bin/activate
        uv pip install -r requirements.txt
        uv pip install pytest pytest-cov
    
    - name: Run unit tests
      run: |
        uv run -m pytest src/tests/unit/ -v
    
    - name: Run integration tests
      run: |
        uv run -m pytest src/tests/integration/ -v
    
    - name: Run end-to-end tests
      run: |
        uv run -m pytest src/tests/e2e/ -v
    
    - name: Generate coverage report
      run: |
        uv run -m pytest --cov=src --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
