name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt -e .
    
    - name: Run unit tests with ${{ matrix.python-version }}
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -m src.ml.app
        sleep 6
        uv run -m pytest src/tests/unit/ -v --cov=src --cov-report=xml
    
    - name: Run integration tests with ${{ matrix.python-version }}
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        uv run -m pytest src/tests/integration/ -v --cov=src --cov-report=xml
    
    # - name: Run end-to-end tests with ${{ matrix.python-version }}
    #   env:
    #     PYTHONPATH: ${{ github.workspace }}
    #   run: |
    #     uv run -m pytest src/tests/e2e/ -v
    
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
